### ISSUE TITLE
Sigmap::allbits() removed during rewrite

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#105]
After updating to the latest yosys version, my code broke, because the function allbits() was removed from SigMap.  I use it to create a canonical sigmap as suggested here:

http://stackoverflow.com/questions/32280118/can-does-sigmap-produce-canonical-output

**Comment by cliffordwolf** [comment]
Oops. Sorry for breaking your code. I've now re-added `SigMap::allbits()`. (jfyi: I did not per-se remove allbits(), I rewrote SigMap and did not re-implement the function because it was not used. Now I remember why it was there..)
