### ISSUE TITLE
splitnets -ports doesn't update module instantiations

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#111]
When I run `splitnets -ports`, I expect that the design will still function as before..  However I was finding that modules were still being instantiated using their old ports, rather than the new split versions.

I was finding this on combinatorial_aes https://github.com/jeremysalwen/combinatorial_aes
With the following commands

    read_verilog rtl/aes_128.v rtl/round.v rtl/table.v
    synth -top aes_128
    splitnets -ports
    hierarchy -check

ERROR: Module `expand_key_128' referenced in module `aes_128' in cell `a1' does not have a port named 'in'.

**Comment by cliffordwolf** [comment]
Fixed in commit 1d62f87.

**Comment by jeremysalwen** [comment]
Thanks!
