### ISSUE TITLE
read_verilog is very slow when module has many for iterations in an always block

### ISSUE THREAD

**Issue by kc8apf** [cliffordwolf/yosys#114]
read_verilog seems to take exponentially longer reading the following module depending on the number of iterations in the for loop:

    module TestCase(
      input wire clock,

    );

    localparam COUNT = 1600;

    reg buffer[0:COUNT-1];

    always @(posedge clock) begin : GENERATE
      integer ii;

      for(ii = 0; ii < COUNT; ii = ii + 1) begin
        buffer[ii] <= 1'b0;
      end
    end

    endmodule

Time spent by 'yosys -p read_verilog test.v':
* 100 iterations -> 0s
* 200 iterations -> 2s
* 400 iterations -> 8s
* 800 iterations -> 36s
* 1600 iterations -> 160s

The OS X performance tools ([Sample of yosys](https://github.com/cliffordwolf/yosys/files/110653/Sample.of.yosys.txt)) seem to implicate Yosys::AST_INTERNAL::ProcessGenerator::removeSignalFromCaseTree(const std::set<RTLIL::SigBit> &pattern, RTLIL::CaseRule *cs) which is calling Yosys::RTLIL::SigSpec::remove2(const RTLIL::SigSpec &pattern, RTLIL::SigSpec *other).  This form of remove2() calls to_sigbit_pool() to get a pool<RTLIL::SigBit>.  Inside to_sigbit_pool(), it creates a pool<RTLIL::SigBit> and then inserts each each bit of each chunk.  This insert seems to trigger a memory allocation via pool<>::insert calling pool<>::do_insert which does a push_back() on a new vector.  It seems that creating a pool on each call to remove2() is excessive in this case.

**Comment by cliffordwolf** [comment]
For the record: Fixed by PR #115.
