### ISSUE TITLE
manual does not build

### ISSUE THREAD

**Issue by SebKuzminsky** [cliffordwolf/yosys#120]
"make manual" at the top level fails because PRESENTATION_Intro.tex tries to include PRESENTATION_Intro/counter_03.pdf, but no counter_03 exists in the repo.  counter_00, 01, and 02 are all in the PRESENTATION_Intro directory, but no 03.

This problem was observed with yosys-0.6 (5869d26d).

**Comment by cliffordwolf** [comment]
Hmm.. it works for me. Have you built yosys with ABC support? I.e. what is the error you are getting when running `rm *.pdf; make` in `yosys/manual/PRESENTATION_Intro/`?

**Comment by SebKuzminsky** [comment]
You're right, it was an abc-related problem on my side.  Sorry for the noise.
