### ISSUE TITLE
How can I replace GND and VCC nodes

### ISSUE THREAD

**Issue by klammerj** [cliffordwolf/yosys#123]
I'd like to dump an edif file with certain elements replaced. 
mostly works. 
replacing VCC and GND with ONE and ZERO is causing me problems, tho'.
having this in a cells_map.v
does not replace them
```
module  GND (output G); ZERO _TECHMAP_REPLACE_ (.Q(G)); endmodule
module  VCC (output P); ONE _TECHMAP_REPLACE_ (.Q(P)); endmodule
```

\$VCC and \$GND doesn't work either. 

help -cells does not seem to show any constants.

more of that mess there: <https://github.com/klammerj/y40k>

**Comment by klammerj** [comment]
I've used ```hilomap -hicell ONE Q -locell ZERO Q``` now, and that works. 
Unfortunately there are still instances of GND and VCC in the resulting edif file(one each). They are unconnected. Can I get rid of those? How?

**Comment by cliffordwolf** [comment]
I've now added a `-nogndvcc` option to `write_edif` in commit d117893007baa506b702967ac6ee9f70af3c236a that should do the job.
