### ISSUE TITLE
Validating module parameters before they are instantiated will result misleading Warnings when default parameters are nonsense.

### ISSUE THREAD

**Issue by Kmanfi** [cliffordwolf/yosys#124]
Hello,
when design has modules with nonsense default parameters Yosys will give Warnings  like:
"Range select out of bounds on signal `\s_in' at test.v:6: Setting 3 MSB bits to undef."
In cases where codebase has many hundred of instantiated modules this will be issue.
If some of instantiated modules will get poor parameters it's hard to find "real" warnings because of many default parameter Warnings. 
I suggest improvement where Default parameter Warnings will be different compared to parameter check made for instantiated modules.

Here is simple code as an example.
```
module sub_module (s_in, s_out);
parameter NUM = 10; //default
input [7:0] s_in;
output [3:0] s_out;

assign s_out = s_in[NUM:0];

endmodule


module top ( m_out, m_in);
parameter NUM = 3;
input [7:0] m_in;
output [3:0] m_out;

sub_module #(NUM)
	sub_1 (.s_in (m_in), .s_out(m_out));
endmodule
```
Cheers

**Comment by cliffordwolf** [comment]
You are probably using a script like the following:

```
read_verilog test.v
hierarchy -top top
```
If you don't want to elaborate the modules with their default parameters, do something like this instead:

```
read_verilog -defer test.v
hierarchy -top top
```

You can even set the `-defer` parameter as a default option for `read_verilog`:

```
verilog_defaults -add -defer
read_verilog test.v
hierarchy -top top
```

I hope that explanation helps.
