### ISSUE TITLE
Extract -map causes outputs to display as inputs

### ISSUE THREAD

**Issue by DFarce** [cliffordwolf/yosys#156]
Running the extract -map example 1 from the February 2016 tutorial slides (slide 96) causes outputs to appear as inputs (below). The example is supposed to map a multiply-accumulate operation, but the outputs are flipped when run on the current version of yosys. I am not sure if this is a bug inside of the show command, or due to an underlying issue in extract.

![bug](https://cloud.githubusercontent.com/assets/5099107/15001854/fd644db2-114f-11e6-9303-34908f978668.png)

Inputs are as listed:
```
/*macc_simple_test.v*/
module test(a, b, c, d, y);  
input [15:0] a, b;
input [31:0] c, d;
output [31:0] y;
assign
y = a*b + c + d;
endmodule

/*macc_simple_xmap.v*/
module macc_16_16_32(a, b, c, y); 
input [15:0] a, b;
input [31:0] c;
output [31:0] y;
assign y = a*b + c;
endmodule

# Yosys script
read_verilog macc_simple_test.v 
hierarchy -check -top test
extract -map macc_simple_xmap.v;;
show
```

**Comment by cliffordwolf** [comment]
>  I am not sure if this is a bug inside of the show command, or due to an underlying issue in extract.

It is neither. There is no explicit information on a cell what ports are inputs and what ports are outputs. This is inferred from the cell declaration. However, in your example, there is no cell declaration loaded for the `macc_16_16_32` cell type. Simply add something like

    read_verilog -lib macc_simple_xmap.v

somewhere to the script before calling `show`, and `show` will know which ports are in- and outputs. (Alternatively you can call `show -lib macc_simple_xmap.v` to let the show command use the port declarations from `macc_simple_xmap.v`, but not add them to the design in memory.)
