### ISSUE TITLE
opt_clean preserves fanout-less assignment, if LHS has initial value

### ISSUE THREAD

**Issue by eshellko** [cliffordwolf/yosys#161]
I have found that Yosys (0.6 release) doesn't remove buffers (.names / direct assignments) if LHS operand declared in RTL with initial value (like reg q = 0;).
Here is a simple example to check. RTL:
```
// file: test.v
module test_init_keep (input clk, din, ena, output dout);
`ifdef __Q_INIT__
reg q=0;
`else
reg q;
`endif
always@(posedge clk)
if(ena)
q<=din;
assign dout = q;
endmodule
```
makefile:
```
flow-yosys:
	yosys -q -s y.tcl -l yosys.log

```
script:
```
# y.tcl
read_verilog -nolatches -D__Q_INIT__ test.v
hierarchy -top test_init_keep
proc; opt; techmap; opt -fast; hierarchy -check -purge_lib; opt_clean -purge
write_blif -undef - unconn -blackbox test.init.blif
write_verilog -noattr test.init.synth.v

design -reset

read_verilog -nolatches      test.v
hierarchy -top test_init_keep
proc; opt; techmap; opt -fast; hierarchy -check -purge_lib; opt_clean -purge
write_blif -undef - unconn -blackbox test.blif
write_verilog -noattr test.synth.v
```

In 1-st case design compiled with 'reg q = 0;' in 2-nd with 'reg q;'.
After synthesis 1-st blif contains unused buffer:
```
.names dout q
1 1
```
Which in my opinion should be removed, as INIT attribute of 'q' doesn't have meaning (actually it kept as .latch initial attribute in blif).

**Comment by cliffordwolf** [comment]
I've now added a `-noalias` option to `write_blif` in commit d10dfccabb6bf4b1ba3f334b899f57093b8a0ddc that suppresses the generation of those buffer.
