### ISSUE TITLE
Compiled manual

### ISSUE THREAD

**Issue by slavaim** [cliffordwolf/yosys#163]
Hi,

I believe it would be more friendly to provide a compiled manual version. Trying to compile from TeX source is just a waste of time. I gave it up after spending an hour on it. There is no point to become a TeX guru when 99.9% docs are in txt or pdf format.

**Comment by cliffordwolf** [comment]
That's why there is a compiled version of the manual on the webpage: http://www.clifford.at/yosys/documentation.html

**Comment by slavaim** [comment]
Thank you!
