### ISSUE TITLE
Parse error on multi-dimensional arrays

### ISSUE THREAD

**Issue by torgny** [cliffordwolf/yosys#167]
yosys 0.6 reports a parse error on the following code when read by the read_verilog command:
`module bar();
  reg [7:0][7:0] foo;
endmodule`

**Comment by torgny** [comment]
I've learned that this i SystemVerilog syntax. Ignore this issue at your convenience. :)

**Comment by cliffordwolf** [comment]
SV features like that are on the long-term todo list for yosys. I'm closing this issue anyways because I organizing my long-term roadmap differently (not using github issues).
