### ISSUE TITLE
YOSYS crashs when using SCC pass after Submod pass

### ISSUE THREAD

**Issue by mithridate** [cliffordwolf/yosys#171]
I was trying to partition my design (a simple counter)  and found it crashes. You can reproduce the crash if you follow these commands

> read_verilog counter.v
> proc; opt; fsm; opt; memory; opt; techmap; opt
> scc -all_cell_types
> and then put each found SCC into a module using submod.
> scc -all_cell_types

then I received:

> ERROR: Assert `workQueue.count(cell) > 0' failed in passes/cmds/scc.cc:57.

I have also included the log of the crash. 
I investigated the crash and here is my observations:
**1. when performing "submod". it cannot figure out the port direction. This create ambiguity for SCC pass and it causes the crash. (it adds up fake SCCs)
2. It can be avoided if  " we first run splitnets -ports -driver" and then "submod".** 

Design:
```
module counter (clk, rst, en, count);
   input clk, rst, en;
   output reg [3:0] count;
   always @(posedge clk)
      if (rst)
         count <= 4'd0;
      else if (en)
         count <= count + 4'd1;
endmodule
```

[crash_report.txt](https://github.com/cliffordwolf/yosys/files/272947/crash_report.txt)

**Comment by cliffordwolf** [comment]
Thanks for reporting this issue. Fixed in commit 611f121cb9fb8a451e891356a6260f4b299afc7d.
