### ISSUE TITLE
$assert cells should be ignored during synthesis

### ISSUE THREAD

**Issue by whitequark** [cliffordwolf/yosys#177]
This was triaged from openfpga, so please see the discussion over at https://github.com/azonenberg/openfpga/issues/11.

**Comment by cliffordwolf** [comment]
The usual approach is to enclose all code for formal verification with \`ifdef FORMAL ... \`endif and only set the define FORMAL when doing formal verification (done by default by `read_verilog -formal`).

It would be possible, as @azonenberg suggested, to add an option to `synth_greenpak4` that simply runs a command such as `delete t:$assert` for convenience, but that would be very unconventional. I'd accept such a patch for `synth_greenpak4` from @azonenberg, but I would not add it to "my" synthesis flows such as `synth_ice40` or `synth_xilinx`.

**Comment by antonblanchard** [comment]
Thanks, I guess the SystemVerilog reproducer was a bit of a red herring. Should GHDL not emit Assert entries at all, or have an option to not emit them? It seems a bit strange to be doing it there, vs yosys or nextpnr.
