### ISSUE TITLE
Readmem finish_addr problem

### ISSUE THREAD

**Issue by eshellko** [cliffordwolf/yosys#209]
I have faced issue when using $readmemh function to emulate ROM initial value.
To reproduce problem I've created ROM with 4 8-bit entries and have used `$readmemh("rom.hex",0,3);` function to initialize ROM with {8'hEE, 8'hCC, 8'h33, 8'h55} value.
During techmap $mem has parameter:
`Parameter \INIT = 25'x110011000011001101010101`
If I change $readmem to `$readmem(...0, 4);`
\INIT looks like this (correct one):
`Parameter \INIT = 32'11101110110011000011001101010101`

The problem is in fronetends/ast/simplify.cc. Function '*AstNode::readmem' breaks reading cycle at line 2472 on event (cursor == finish_addr). But actual assigning to the rom[finish_addr] wasn't made yet.

2466:			if ((cursor == finish_addr) || (increment > 0 && cursor > range_max) || (increment < 0 && cursor < range_min))
2467:				break;
2468:			cursor += increment;
2469:		}
2470:
2471:		if ((cursor == finish_addr) || (increment > 0 && cursor > range_max) || (increment < 0 && cursor < range_min))
2472:break;

**Comment by cliffordwolf** [comment]
Thanks for the bug report! Fixed in commit fe9315b.
