### ISSUE TITLE
feature request: C entrypoints for libyosys

### ISSUE THREAD

**Issue by nturley** [cliffordwolf/yosys#220]
I was experimenting with libyosys and I ran into some difficulties. All of the entry points into the shared library are C++ entrypoints instead of C entrypoints. It would be nice to have a C API layer.

C entry points are obviously nice if you want to call into the shared library from C, but it also makes the shared library more portable even if you are calling it from C++ because not all C++ compilers, or even versions of the same C++ compiler, are ABI compatible. Also C entrypoints make it easier to call into the library from non-C languages like python using foreign function interfaces like ctypes.

I think that all you would have to do is pick a few useful entrypoints into the API, add functions that call into them, converting any c++ structures to C, and exporting the symbols with "extern c".

**Comment by cliffordwolf** [comment]
> converting any c++ structures to C

yeah. I'm not going to do that. That would for example mean replacing all the C++ containers (like dict<> and pool<>) with something that can be accessed from C, which essentially means rewriting Yosys.

Yosys is written in C++11. If you want to do more with the API than you can do with a Yosys script, then you will need to be able to e.g. call methods of objects and do other C++ stuff. If all you want to do is call a sequence of Yosys passes, then why not simply write a Yosys script?
