### ISSUE TITLE
read_liberty (again), issue with bus_type

### ISSUE THREAD

**Issue by leviathanch** [cliffordwolf/yosys#236]
Hello
The last commit fixed the issue with loading the liberty file for the cell with the SRAM but instead broke the loading of the Flash cells.
Now it says `ERROR: Unkown or unsupported type for bus interface Q on cell X...`

**Comment by cliffordwolf** [comment]
Fixed in commit 8f5bf6de32bcc478312d8f5410826b4894ebadba.

**Comment by leviathanch** [comment]
Thanks! Fixed it!
