### ISSUE TITLE
yosys won't pass its default "make test"

### ISSUE THREAD

**Issue by sixshotx** [cliffordwolf/yosys#241]
OS: *Archlinux*
Compiler: *g++ 6.2.1*

Symptom:
After **yosys** is compiled, running `make test` throws the following error.
```log
make[1]: Entering directory '/home/sixshotx/yosys/tests/bram'
../../techlibs/common/simlib.v:1757: error: Enable of unknown task ``ns''.
1 error(s) during elaboration.
make[1]: *** [temp/makefile:3: temp/job_00_01.ok] Error 1
make[1]: Leaving directory '/home/sixshotx/yosys/tests/bram'
make: *** [Makefile:422: test] Error 2
```

**Comment by cliffordwolf** [comment]
Usually when `make test` fails its because the user is having an older version of iverilog than I am using. In this case you are using a newer version.

I've updated my installation to latest iverilog git head and fixed the problem in Yosys commit 4a981a3.
