### ISSUE TITLE
README file link broken on website after markdownification

### ISSUE THREAD

**Issue by oldtopman** [cliffordwolf/yosys#276]
In commit d4e15926099244eabdeee2515a11da6e840ef495, README was renamed to README.md. This broke the README link on your website [here](http://www.clifford.at/yosys/documentation.html).

**Comment by cliffordwolf** [comment]
Thanks! Fixed: https://github.com/cliffordwolf/yosys-web/commit/265f5e197cedfac5c5e61d6cfed1e8000a3825f1
