### ISSUE TITLE
Request inclusion of man pages from Debian

### ISSUE THREAD

**Issue by brouhaha** [cliffordwolf/yosys#278]
In the Fedora package review, it has been suggested that it might be a good idea for the man pages provided from Debian be added to the official yosys repository and releases.  As of this writing, they can be found in a tarball at:
    http://dist1.800hosting.com/debian/pool/main/y/yosys/yosys_0.7-2.debian.tar.xz
However, the URL changes every time the Debian package is revised.

If you'd like me to to add them and submit a pull request, let me know.

**Comment by cliffordwolf** [comment]
I'll accept a pull request that adds the man page. Please coordinate with the debian package maintainer @rubund to guarantee a smooth transition regarding the primary location of the man page.
