### ISSUE TITLE
unique / priority case

### ISSUE THREAD

**Issue by OrDavidi** [cliffordwolf/yosys#297]
Hi,
systemverilog has the weird syntax : 
unique case  / priority case.
as far as i understand this syntax it is just normal case with synthesis instructions.
i add this support to the lexer and parser locally. do you mind adding it as well  ? 

lexer : 
"unique"      {return  TOK_UNIQUE;}
"priority"   {return  TOK_PRIORITY;}

parser : 
%token TOK_MODULE TOK_ENDMODULE TOK_PARAMETER TOK_LOCALPARAM TOK_DEFPARAM TOK_UNIQUE TOK_PRIORITY

case_type:
    TOK_CASE {
		case_type_stack.push_back(0);
	} |
    TOK_UNIQUE TOK_CASE {
		case_type_stack.push_back(0);
	} |
TOK_PRIORITY TOK_CASE {
		case_type_stack.push_back(0);
	} |
	TOK_CASEX {
		case_type_stack.push_back('x');
	} |
	TOK_CASEZ {
		case_type_stack.push_back('z');
	};

Thanks

**Comment by cliffordwolf** [comment]
Commit 00dba4c adds support for `unique`, `unique0`, and `priority` case/casex/casez.
