### ISSUE TITLE
$logic_and to wire special case

### ISSUE THREAD

**Issue by mtuomi** [cliffordwolf/yosys#307]
```
module logic_and_to_wire (input a, output y);
    assign y = (a && 1'b1);
endmodule

```
Looks like there is special case handling for this in opt_expr.cc: 
```
if (cell->type.in("$and", "$logic_and") && GetSize(cell->getPort("\\A")) == 1 && GetSize(cell->getPort("\\B")) == 1)
	detect_const_and = true;

```

Should opt -full convert this to wire?

**Comment by cliffordwolf** [comment]
I've now added an optimization for this in commit a5bfeb9.

> Looks like there is special case handling for this in opt_expr.cc

That code was only handling `(a && 1'b0)` and `(a || 1'b1)`. I've now added support for the cases where and AND/OR turns into a buffer instead of a constant.
