### ISSUE TITLE
Warning: Resizing cell port big_test.O12.PAD from 5 bits to 1 bits.

### ISSUE THREAD

**Issue by klammerj** [cliffordwolf/yosys#310]
I'm getting loads of these. 
The primitives in question are wide io ports in cells_map.v and cells_sim.v. 
They have all 1 additional parameter WIDTH. and their arguments are wide signals, too. 
I'd like to use techmap to replace them with single bit primitives. 
but on the hierarchy pass I'm getting above messages already. 
What am I doing wrong?
The whole setup is here: 
https://github.com/klammerj/y40k
The command I used:
```
./y40k.sh ./test/big_test.v ./test/big_test.edf &>asdf.log
```
(I've uploaded that logfile, too)

yosys was just pulled and compiled/installed and is at commit: 
```
commit cdb6ceb8c63f2c38bdba3f66be7c444def43897e
Author: Clifford Wolf <clifford@clifford.at>
Date:   Sat Feb 11 15:57:36 2017 +0100

    Add support for verific mem initialization
```

**Comment by cliffordwolf** [comment]
Oops! Thanks for reporting this issue. Fixed in commit 76c4ee0.
