### ISSUE TITLE
Feature request ( ++,-- support)

### ISSUE THREAD

**Issue by OrDavidi** [cliffordwolf/yosys#317]
Can you please add support in ++,-- usage (SV syntax) 
for example  : 
integer b;
 generate
    for (b=0; b<BUFFS; **b++**) begin : inp_gen
      assign rdy_in[b] = tx_1588_rdy_x[b];
      assign stb_in[b]  = ifc_mac_tx_val_x[b];
    end
  endgenerate
Thanks!

**Comment by cliffordwolf** [comment]
Done in commit 34d4e72.
