### ISSUE TITLE
ICE40 DDR output simulation not matching oscope

### ISSUE THREAD

**Issue by dlharmon** [cliffordwolf/yosys#330]
The output of Icarus/GTKWave using cells_sim.v matches what I'd expect from the ICE tech library document. 

When synthesized and loaded in hardware, it appears as if D_OUT_0 and D_OUT_1 were swapped.

Simplified code to demonstrate issue: 
```
reg [1:0] ledi;
   always @ (posedge clockbuf)
     begin
        case(count[5:0])
          0: ledi <= 2'b00;
          1: ledi <= 2'b11;
          2: ledi <= 2'b01;
          3: ledi <= 2'b10;
          4: ledi <= 2'b00;
          5: ledi <= 2'b11;
          6: ledi <= 2'b00;

          default: ledi <= 2'b11;
        endcase
     end

   SB_IO #(.PIN_TYPE(6'b110000), .IO_STANDARD("SB_LVCMOS")) led_ddr
     (.PACKAGE_PIN(led),
      .CLOCK_ENABLE(1'b1),
      .OUTPUT_CLK(clockbuf),
      .OUTPUT_ENABLE(1'b1),
      .D_OUT_0(ledi[0]), // data out to pin                                                                                              
      .D_OUT_1(ledi[1]));
```

![lecroy23](https://cloud.githubusercontent.com/assets/6054322/23815028/3d8667f2-05a3-11e7-9ce0-b14b1dd9df29.png)

![ice40ddr](https://cloud.githubusercontent.com/assets/6054322/23815016/2f5925fc-05a3-11e7-97f7-5e66b20e9131.png)

Note the difference in the order of the output bits.
00 11 01 10 00 11 00 for simulation
00 11 _10 01_ 00 11 00 in hardware

led and clockbuf in the GTKWave trace are the two signals on the scope.

The chip is an ICE40HX1K.
I'm currently planning to work around it by doubling the clock frequency.

**Comment by cliffordwolf** [comment]
Is it possible that this is related to https://github.com/cseed/arachne-pnr/issues/61 and is fixed by https://github.com/cseed/arachne-pnr/pull/62?

Btw: Less than an [mcve](http://stackoverflow.com/help/mcve) is not very helpful. Just posting code snippets instead of a minimal example that I can actually run prevents me from reproducing the thing you are observing.

**Comment by dlharmon** [comment]
It was fixed by https://github.com/cseed/arachne-pnr/pull/62. Thanks!
