### ISSUE TITLE
Support localparam in module parameter list (v2009)

### ISSUE THREAD

**Issue by udif** [cliffordwolf/yosys#342]
Please see discussion and example here:
https://www.veripool.org/boards/2/topics/1820-Verilator-support-for-localparam-in-parameter-port-list

I have a code base I'm moving back and forth between yosys, verilator, vcs and a few others, and trying to reach feature-parity :-)

Thanks in advance!

**Comment by cliffordwolf** [comment]
Implemented in e91548b.
