### ISSUE TITLE
Add error for constant connection to output port

### ISSUE THREAD

**Issue by OrDavidi** [cliffordwolf/yosys#362]
Hi , 
can you please add error if such case happen : 

module inst(a,b);
   output b;
   input a;
   assign b = ~a;
endmodule

module top(a,b);
   input a;
   output b;
inst inst(
.a(a),
.b(1'b1)
);
endmodule

iverilog gives this error : 
top.v:12: error: expression not valid in assign l-value: 1'd1
top.v:12: error: Output port expression must support continuous assignment.
top.v:12:      : Port b of inst is connected to 1'd1
1 error(s) during elaboration.

yosys gives no error.

Thanks

**Comment by cliffordwolf** [comment]
Implemented in b6bd12f. (As part of the "hierarchy" pass.)
