### ISSUE TITLE
Space character in path breaks synthesys

### ISSUE THREAD

**Issue by Gl237man** [cliffordwolf/yosys#375]
Executing abc command in yosys script fails when the path to liberty file contains space character.
The path quoting for abc doesn't work propperly, for absolute paths.
dfflibmap command works correctly with paths.

Found this problem on windows.

**Comment by cliffordwolf** [comment]
I don't see how this would work if dfflibmap because this command, like abc, breaks arguments at white spaces.

I'm sorry, this is a wontfix: Don't use path names that contain blanks.
