### ISSUE TITLE
dff2dffe

### ISSUE THREAD

**Issue by Kmanfi** [cliffordwolf/yosys#402]
Been wondering why cell count does't change after running dff2dffe. If I run opt or opt -fine it doesn't change situation. Only when running opt -full it detects constant selectors on $muxes. I suggest connecting one of the $mux input directly to D, S to E, and delete $mux.
When doing synthesis tests with big designs opt -full...... take time :)
```
module add_conated_const (CLK, a, e, x);
input CLK;
input e;
input [1:0] a;
output [1:0] x;

  reg  [1:0] x;

  always @(posedge CLK) begin
    if (e)
	begin
	    x <= x;
	end else begin			
	    x <= a;
	end;
   end
endmodule

```

**Comment by cliffordwolf** [comment]
> Only when running opt -full it detects constant selectors on $muxes.

That's intentional.
