### ISSUE TITLE
Asserting and assuming the same initial property causes a failure

### ISSUE THREAD

**Issue by ZipCPU** [cliffordwolf/yosys#447]
As the topic says, asserting and assuming the same initial value fails.  It doesn't seem to matter which solver is used, the preconditions somehow always fail.

I've found that, within a given module, it makes sense to assert outputs and assume inputs.  However, when I tried to encapsulate some of these checks into a sub-module, asserting values that were inputs to both the submodule and the top level module the design failed to satisfy its preconditions.  If I turned --presat off, the design still fails quickly.

You should be able to find an example of this at [zipcpu.com/tmp/ybug.tgz](http://zipcpu.com/tmp/ybug.tgz) (since I can't seem to upload TGZ files here ...).  The "runme.sh" command within there (4 lines long) is sufficient to generate the bug.

Dan

**Comment by cliffordwolf** [comment]
Mea culpa, that was a really stupid bug. Fixed in 455c1c9. Thanks for the great test case.
