### ISSUE TITLE
BUG: Delays with fractional time values cause syntax errors

### ISSUE THREAD

**Issue by azonenberg** [cliffordwolf/yosys#451]
According to the LRM, "delay_value" can be an unsigned, a real, or an identifier. Yosys appears to only accept integer valued delays when parsing source files. This causes syntax errors in e.g. cells_sim.v for GreenPAK.

- WORKS:  "#99"
- FAILS: "#99.123"

**Comment by cliffordwolf** [comment]
Fixed in 5b6e521.
