### ISSUE TITLE
SMT2 file left behind upon failure

### ISSUE THREAD

**Issue by ZipCPU** [cliffordwolf/yosys#463]
I have a design that fails to build an SMT2 file via yosys.  (The design likely has a bug.)  However, yosys leaves behind an SMT2 file--despite the fact that it returned a failing error code.  This can then be used in a make script (erroneously) assuming that the SMT2 file was created validly, leading to further problems down the road.

```sh-4.3$ make axim2wbsp
yosys -ql axim2wbsp.yslog -s axim2wbsp.ys
ERROR: Unsupported cell type $shiftx for cell $paramod$81c5029e495907570fed704a1cc87bca34548adb\aximwr2wbsp.$shiftx$../../rtl/aximwr2wbsp.v:258$4723.
Makefile:65: recipe for target 'axim2wbsp.smt2' failed
make: *** [axim2wbsp.smt2] Error 1
sh-4.3$ make axim2wbsp
rm -f axim2wbsp.check
yosys-smtbmc --presat -s yices -t 36 --dump-vcd axim2wbsp.vcd axim2wbsp.smt2
##      0   0:00:00  Solver: yices
Traceback (most recent call last):
  File "/usr/local/bin/yosys-smtbmc", line 400, in <module>
    assert topmod is not None
AssertionError
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

A second but related issue is that yosys-smtbmc fails to properly crash on error--it needs to be killed with a control C.

Dan

**Comment by cliffordwolf** [comment]
None of the back-ends removes output files if an error occurs while the output file is written. Make has the special built-in target `.DELETE_ON_ERROR` that will cause make to remove the output file in this case. I'd recommending using this target if you want the output file to be removed.
