### ISSUE TITLE
Installation is needed to create the manual

### ISSUE THREAD

**Issue by set-soft** [cliffordwolf/yosys#477]
The `make manual` target needs a `make install` first. This isn't a good idea.
The problem is that `manual/PRESENTATION_Prog/Makefile` invokes `../../yosys-config` but this script uses the system level location for the includes, instead of `../..`
IMHO the yosys-config script should be invoked passing `-I../..` option to use the current files, not the system wide ones. They can be from other yosys version, or just not installed.

I'm using this:
[0010-Manual-build-fix.txt](https://github.com/cliffordwolf/yosys/files/1600263/0010-Manual-build-fix.txt)

**Comment by cliffordwolf** [comment]
You are right of course, it should not use the Yosys installed in the system. But I'll nevertheless close this as WONTFIX because we will (hopefully soon) move the manual to a separate github repository, and then the fix will be not to use `../../yosys-config`.
