### ISSUE TITLE
Feature Request: Expose select_op_diff, etc through the API

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#49]
It would be nice to be able to manipulate selections with the same functions that the "select" command uses.

I'm not sure if it would be feasible to integrate such functionality into the RTLIL::Selection class.

**Comment by cliffordwolf** [comment]
Here you go: 09ee65a050ffc8fe1a208140cce32a6a5f15c4ab (and bcd8a2fc567e0bbc1b04467ac7a3b32ed332f7f3, oops ;).

Usage example:

    vector<RTLIL::Selection> work;
    work.push_back(RTLIL::Selection());
    work.push_back(eval_select_args({"n:a*", "n:*a", "%i"}, design));
    eval_select_op(work, "%d", design);

The call to `eval_select_op()` in that example is practically a direct call to `select_op_diff()`.

**Comment by jeremysalwen** [comment]
Thanks!
