### ISSUE TITLE
splice command not working on logic_not

### ISSUE THREAD

**Issue by ahmedirfan1983** [cliffordwolf/yosys#58]
splice command is not working on the following model:

module main(a,b);
       input a;
       output b;
       integer i;
       assign i = !a;
       assign b = i[0];
       assert property (b == !a);
endmodule

after reading the file, I run the following commands

proc; opt; splice;

There is a logic_not cell that has a output of width 32, but it should have output width 1.

cell $logic_not $logic_not$logicnot.v:6$1
    parameter \A_SIGNED 0
    parameter \A_WIDTH 1
    parameter \Y_WIDTH 32
    connect \A \a
    connect \Y { \i [31:1] $auto$splice.cc:234:run$7 }
  end

**Comment by cliffordwolf** [comment]
The "splice" command does not change the width of operators. That's what the "wreduce" command does. I have now added handling of bool-outputs to wreduce in commit e305d858075902cdfe277f36ce52f8e01de65f7e.

Note: run "clean" after "splice" (or simply "splice;;") to clean up the bit messy configuration of wires at the "Y" output in the example you gave.
