### ISSUE TITLE
Colon in comments in the  synthesis script (-s projekt.ys)

### ISSUE THREAD

**Issue by m-temp** [cliffordwolf/yosys#59]
Hallo,

I've detected a possible bug (or feature?) in the handling of the synthesis script (-s projekt.ys):
I've added the following comment:
```
#Myname: added "-purge" to remove unneeded buffers
```
Now, I get the following error:
>15.9. Finished OPT passes. (There is nothing left to do.)
>ERROR: No such command: added (type 'help' for a command overview) outputprep failure:  No file map9v3_mapped.blif.
>Premature exit.
To me it seems like the colon closes the comment...

If I change the comment to
```
#Myname added "-purge" to remove unneeded buffers
```
(Notice the missing colon!) Everything works!

I'm using qflow with yosys from this ppa: https://launchpad.net/~saltmakrell/+archive/ubuntu/ppa

**Comment by cliffordwolf** [comment]
Good catch! Thanks for reporting.

Fixed it in commit cfdc9fc50ed3280fb1e048bbf6125f009ab44403.
