### ISSUE TITLE
freduce segfault

### ISSUE THREAD

**Issue by wluker** [cliffordwolf/yosys#67]
The freduce command segfaults when there is a loop in combinational logic. I had accidently made a loop in my code which uncovered the segfault. I wouldn't expect freduce to work on these loops, but rather throw an error.

Even simple test cases should reproduce the issue:

    module test(input en, output reg y);
      always @*
        y = en & !y;
    endmodule

**Comment by cliffordwolf** [comment]
Ooops. Thanks for bringing this to my attention. Fixed in commit ee9188a5b4013f22d2694d4c3e5bb7d08438bfb3.

**Comment by wluker** [comment]
Wow, that was fast. Thank you.
