### ISSUE TITLE
ConstEval API

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#74]
I'm trying to write a plugin that requires evaluating combinatorial circuits.  From what I can gather ConstEval is the tool which does this.  However, the API is not so clear to me.  Is there somewhere a rundown of the members of ConstEval and what they do?

**Comment by cliffordwolf** [comment]
I have now posted an answer to that question to stackoverflow: http://stackoverflow.com/questions/32093541/how-does-the-yosys-consteval-api-work

Feel free to ask followup questions either here or there.
