### ISSUE TITLE
dict<K,V> does not have const operator[]

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#76]
It might be nice to have a const operator[] in the dict class, for accessing elements from const dicts.

**Comment by cliffordwolf** [comment]
`T& dict<>::operator[](const K &key)` creates the entry with its default constructor when it is not already in the dict. You can't do that with a `const dict<>`. Use `const T& dict<>::at(const K &key) const` to access an already existing entry (throws `std::out_of_range` for non existing entries).
