### ISSUE TITLE
splitnets misorders input port

### ISSUE THREAD

**Issue by jeremysalwen** [cliffordwolf/yosys#78]
I have a very specific bug with splitnets that I can only seem to reproduce with these exact settings:

Running the commands

    read_verilog input.v
    hierarchy
    splitnets -ports
    write_verilog output.v

on this file: http://pastebin.com/d00zh74b  creates this output that begins

```
* Generated by Yosys 0.5+284 (git sha1 f40d1b7, gcc 5.2.1-15 -fPIC -Os) */

(* src = "test.v:1" *)
module is28(\X[1] , \X[0] , \X[2] , \X[3] , \X[4] , \X[5] , \X[6] , \X[7] , \X[8] , \X[9] , Y);
  (* src = "test_synth.v:3825" *)
  wire _03796_;
  (* src = "test_synth.v:3826" *)
```

if I run opt before splitnets or hierarchy it outputs 

```
/* Generated by Yosys 0.5+284 (git sha1 f40d1b7, gcc 5.2.1-15 -fPIC -Os) */

(* src = "test.v:1" *)
module is28(\X[9] , \X[8] , \X[7] , \X[6] , \X[5] , \X[4] , \X[3] , \X[2] , \X[0] , \X[1] , Y);
  (* src = "test_synth.v:3825" *)
  wire _03796_;
  (* src = "test_synth.v:3826" *)
```

I'm not sure which way the split wires are supposed to be ordered, but both of them have 0 and 1 in the wrong order.

If i save the intermediate result to a file between hierarchy and splitnets, it does not reproduce.

**Comment by cliffordwolf** [comment]
Thanks for bringing this problem to my attention! Fixed in 6f9a6fd783dcca871ab89890aa9cde7add648f1e.
